services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: vivek # edit password if needed

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
